# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRv8cAQxf545w29_uHjTsNTmrn3D7sXh
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import streamlit.components.v1 as components
# 
# # Set background image
# page_bg_img = '''
# <style>
# .stApp {
# background-image: url("https://raw.githubusercontent.com/ImperviousKing1202/KazuyaSensei/main/HOME.jpg");
# background-size: cover;
# background-repeat: no-repeat;
# background-attachment: fixed;
# }
# </style>
# '''
# 
# st.markdown(page_bg_img, unsafe_allow_html=True)
# 
# st.markdown("<h1 style='color: white; text-align: center;'>🔬 ChemistryLab</h1>", unsafe_allow_html=True)
# st.markdown("<h3 style='color: white; text-align: center;'>Explore, Experiment, Learn!</h3>", unsafe_allow_html=True)
# 
# # Navigation
# option = st.sidebar.selectbox("Navigate", ["🏠 Home", "📊 Periodic Table", "🧪 Drag & Drop Lab", "🔥 Simulate Reactions"])
# 
# # Page 1: Home
# if option == "🏠 Home":
#     st.markdown("<p style='color:white'>Welcome to the virtual Chemistry Lab! Choose a module from the sidebar to begin.</p>", unsafe_allow_html=True)
# 
# # Page 2: Periodic Table
# elif option == "📊 Periodic Table":
#     st.subheader("🧩 Simple Periodic Table Preview")
#     st.image("https://upload.wikimedia.org/wikipedia/commons/0/01/Periodic_table_large.png", use_column_width=True)
#     st.info("Click the image for a full view. Interactive version coming soon!")
# 
# # Page 3: Drag & Drop Lab (Prototype only)
# elif option == "🧪 Drag & Drop Lab":
#     st.subheader("🔧 Drag & Drop Lab (Prototype)")
#     st.markdown("Simulate combining chemicals by choosing elements and combining them.")
# 
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         element1 = st.selectbox("Choose first element", ["", "Na (Sodium)", "HCl (Hydrochloric Acid)", "Vinegar", "Baking Soda"])
#     with col2:
#         element2 = st.selectbox("Choose second element", ["", "Cl (Chlorine)", "NaOH (Sodium Hydroxide)", "Baking Soda", "Vinegar"])
# 
#     if st.button("Mix Elements"):
#         if (element1 == "Vinegar" and element2 == "Baking Soda") or (element2 == "Vinegar" and element1 == "Baking Soda"):
#             st.success("💥 Reaction: CO₂ released! Fizzing effect observed.")
#             st.image("https://media.giphy.com/media/l0MYC0LajbaPoEADu/giphy.gif", caption="Bubbling Reaction", use_column_width=True)
#         elif element1 and element2:
#             st.warning(f"⚗️ Mixing {element1} and {element2}... No observable reaction yet.")
#         else:
#             st.info("Select two elements to simulate.")
# 
# # Page 4: Simulate Reactions (Simple Visuals)
# elif option == "🔥 Simulate Reactions":
#     st.subheader("⚛️ Chemical Reactions Simulation")
#     st.markdown("Select a common reaction to visualize.")
# 
#     reaction = st.selectbox("Choose a reaction", [
#         "Select...",
#         "Baking Soda + Vinegar",
#         "Sodium + Water (Coming soon)",
#         "Hydrochloric Acid + Sodium Hydroxide (Coming soon)"
#     ])
# 
#     if reaction == "Baking Soda + Vinegar":
#         st.markdown("**Reaction:** NaHCO₃ + CH₃COOH → CO₂ + H₂O + CH₃COONa")
#         st.image("https://media.giphy.com/media/l0MYC0LajbaPoEADu/giphy.gif", use_column_width=True)
#         st.success("Carbon dioxide gas is released — bubbling/fizzing observed!")
#     elif "Coming soon" in reaction:
#         st.warning("🔧 Reaction simulation is under development. Stay tuned!")
#